<?php
$doc = new DOMDocument("1.0", "UTF-8");
$doc->formatOutput = true;
$movieinfo= $doc->createElement("MovieInfo");
$doc->appendChild($movieinfo);
$movie= $doc->createElement("category");
$movie->setattribute("type","Horror");
$movieinfo->appendChild($movie);
$mno= $doc->createElement("mno","1");
$movie->appendChild($mno);
$mname= $doc->createElement("moviename","Raven");
$movie->appendChild($mname);
$aname= $doc->createElement("actorname","Kelly");
$movie->appendChild($aname);
$year= $doc->createElement("year","2010");
$movie->appendChild($year);
$movie= $doc->createElement("category");
$movie->setattribute("type","Classic");
$movieinfo->appendChild($movie);
$mno= $doc->createElement("mno","2");
$movie->appendChild($mno);
$mname= $doc->createElement("moviename","Impossible");
$movie->appendChild($mname);
$aname= $doc->createElement("actorname","Bradd pitt");
$movie->appendChild($aname);
$year= $doc->createElement("year","2016");
$movie->appendChild($year);
$movie= $doc->createElement("category");
$movie->setattribute("type","Action");
$movieinfo->appendChild($movie);
$mno= $doc->createElement("mno","3");
$movie->appendChild($mno);
$mname= $doc->createElement("moviename","Jersey");
$movie->appendChild($mname);
$aname= $doc->createElement("actorname","Sahid");
$movie->appendChild($aname);
$year= $doc->createElement("year","2015");
$movie->appendChild($year);
$movie= $doc->createElement("category");
$movie->setattribute("type","Horror");
$movieinfo->appendChild($movie);
$mno= $doc->createElement("mno","4");
$movie->appendChild($mno);
$mname= $doc->createElement("moviename","Run");
$movie->appendChild($mname);
$aname= $doc->createElement("actorname","Ryan");
$movie->appendChild($aname);
$year= $doc->createElement("year","2010");
$movie->appendChild($year);
$movie= $doc->createElement("category");
$movie->setattribute("type","Action");
$movieinfo->appendChild($movie);
$mno= $doc->createElement("mno","5");
$movie->appendChild($mno);
$mname= $doc->createElement("moviename","Jumanji");
$movie->appendChild($mname);
$aname= $doc->createElement("actorname","Rock");
$movie->appendChild($aname);
$year= $doc->createElement("year","2010");
$movie->appendChild($year);
$doc->save("movie.xml");
echo "movie.xml created<h4>";
?>

